### PR TITLE
add(test): add basic test-suite

### PR DESCRIPTION
**Pull request by robinboehm**
Hey I've added some basic tests.
If you like, you could add also travisCI support for automated testing at commits.

https://travis-ci.org/L1fescape/curtsy

### CODE REVIEW

**Comment by robinboehm** [comment]
Test already uncovered a bug...and fixed this with @PascalPrecht =)

**Comment by 0x-r4bbit** [comment]
:v:

**Comment by L1fescape** [comment]
Awesome @robinboehm and @PascalPrecht, thanks a ton! :+1:

**Comment by 0x-r4bbit** [comment]
Well.. it's christmas time, right? Have fun with it! haha

On Tue, Dec 3, 2013 at 4:31 PM, Andrew Kennedy notifications@github.comwrote:

> Awesome @robinboehm https://github.com/robinboehm and @PascalPrechthttps://github.com/PascalPrecht,
> thanks a ton! [image: :+1:]
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/L1fescape/curtsy/pull/4#issuecomment-29719114
> .

## 

/pp

**Comment by robinboehm** [comment]
Christmas PR Chain... :)

**Pull request merged**
